"""empty message

Revision ID: 8c9e76b2dce0
Revises: 42550b559ccd
Create Date: 2023-07-19 13:50:45.906225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9e76b2dce0'
down_revision = '42550b559ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorite_book', sa.String(length=250), nullable=False),
    sa.Column('favorite_genres', sa.String(length=250), nullable=False),
    sa.Column('favorite_author', sa.String(length=250), nullable=False),
    sa.Column('number_books_read', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discussion_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=256), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favorite_book')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_book', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.drop_column('title')

    op.drop_table('comments')
    op.drop_table('profile')
    # ### end Alembic commands ###
