"""empty message

Revision ID: c8aa85067565
Revises: 42550b559ccd
Create Date: 2023-07-17 12:32:18.047001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8aa85067565'
down_revision = '42550b559ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorite_book', sa.String(length=250), nullable=True),
    sa.Column('favorite_genres', sa.String(length=250), nullable=True),
    sa.Column('favorite_author', sa.String(length=250), nullable=True),
    sa.Column('number_books_read', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favorite_book')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_book', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    op.drop_table('profile')
    # ### end Alembic commands ###
